server:
  port: 8005
mybatis:
  type-aliases-package: com.zk.cloudalibaba.entities
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: nacos-passport-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos地址
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mydb?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: test
    password: test
#消费者要去访问的微服务名称，这里配置注册进nacos的微服务提供者
service-url:
  nacos-department-service: http://cloud-department-service
  nacos-account-service: http://cloud-account-service

management:
  endpoints:
    health:
      show-details:always
    web:
      exposure:
        include: health,info
